#spring:
#  profiles:
#    active: dev

server:
  port: 8888

#MySQL配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    password: root
    username: root

  #jsp配置
  mvc:
    view:
      suffix: .jsp
      prefix: /WEB-INF/jsp/

#mybatis配置
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.blue.hospotal.entity


#showsql
logging:
  level:
    com:
      blue:
        hospital:
          mapper: debug